"""
Django settings for recordatin project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path: Path) -> None:
    """Carga KEY=VALUE desde un archivo .env sin dependencia externa."""
    if not path.is_file():
        return
    try:
        for line in path.read_text(encoding='utf-8').splitlines():
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, _, value = line.partition('=')
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value
    except OSError:
        pass


_load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$j4705+q*)ww0esmju__6!@$+h7r)%(jl&m%wx#((15kgzonr9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver', 'spentor.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'paciente',
    'maestro',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'recordatin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'paciente.context_processors.paciente_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'recordatin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'recordatin',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'paciente:medicamentos_hoy'
LOGOUT_REDIRECT_URL = 'login'

# URL base para enlaces QR y SMS (producción). Ej: https://spentor.app
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Web Push (VAPID) — opcional; el canal principal de alarmas es SMS (LabsMobile)
VAPID_PUBLIC_KEY = (
    'BKzF7emho49M5yPDDV-5OW9iSahrJBnxtfEI5bJvRX5_6AD8dFf0-N0J1AWFjCFzp2zB7T3qqgSTXU1B4crm_VY'
)
VAPID_PRIVATE_KEY = str(BASE_DIR / 'vapid_private.pem')
VAPID_CLAIMS_EMAIL = 'mailto:admin@recordatin.local'

# Canal de recordatorios: 'sms' (LabsMobile) o 'push' (Web Push legacy)
NOTIFICACIONES_CANAL = os.environ.get('NOTIFICACIONES_CANAL', 'sms')

# LabsMobile SMS — https://api.labsmobile.com/json/send
# Credenciales por variables de entorno (no subir el token al repo).
LABSMOBILE_USERNAME = os.environ.get('LABSMOBILE_USERNAME', '')
LABSMOBILE_TOKEN = os.environ.get('LABSMOBILE_TOKEN', '')
LABSMOBILE_SENDER = os.environ.get('LABSMOBILE_SENDER', 'Recordatin')
LABSMOBILE_DEFAULT_COUNTRY = os.environ.get('LABSMOBILE_DEFAULT_COUNTRY', '51')  # Perú
