# Generated by Django 4.2.7 on 2026-05-17 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoPrescrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=100)),
                ('via', models.CharField(choices=[('oral', 'Oral'), ('sublingual', 'Sublingual'), ('topica', 'Tópica'), ('inyectable', 'Inyectable')], default='oral', max_length=20)),
                ('instrucciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medicamento prescrito',
                'verbose_name_plural': 'Medicamentos prescritos',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('diagnostico_principal', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='TomaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_programada', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('tomado', 'Tomado'), ('omitido', 'Omitido'), ('tardio', 'Tardío')], default='pendiente', max_length=20)),
                ('hora_registrada', models.DateTimeField(blank=True, null=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomas', to='core.medicamentoprescrito')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomas', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Toma de medicamento',
                'verbose_name_plural': 'Tomas de medicamento',
                'ordering': ['fecha', 'hora_programada'],
            },
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('medico_nombre', models.CharField(max_length=200)),
                ('indicaciones_generales', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Prescripción',
                'verbose_name_plural': 'Prescripciones',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.AddField(
            model_name='medicamentoprescrito',
            name='prescripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='core.prescripcion'),
        ),
        migrations.CreateModel(
            name='HorarioToma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de días: 0=lunes … 6=domingo. Vacío = todos los días.')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.medicamentoprescrito')),
            ],
            options={
                'verbose_name': 'Horario de toma',
                'verbose_name_plural': 'Horarios de toma',
                'ordering': ['hora'],
            },
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('especialidad', models.CharField(max_length=150)),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Cita médica',
                'verbose_name_plural': 'Citas médicas',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='tomamedicamento',
            constraint=models.UniqueConstraint(fields=('medicamento', 'fecha', 'hora_programada'), name='unique_toma_por_horario'),
        ),
    ]
