# Generated by Django 4.2.7 on 2026-05-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ovejitas',
            field=models.PositiveIntegerField(default=0, verbose_name='Ovejitas acumuladas'),
        ),
        migrations.AddField(
            model_name='tomamedicamento',
            name='a_tiempo',
            field=models.BooleanField(blank=True, help_text='True si se registró dentro de los 15 min tras la hora programada.', null=True),
        ),
        migrations.CreateModel(
            name='RegistroRecompensaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('resultado', models.CharField(choices=[('exito', 'Éxito'), ('fallo', 'Fallo'), ('sin_tomas', 'Sin tomas')], max_length=20)),
                ('ovejitas_antes', models.PositiveIntegerField()),
                ('ovejitas_despues', models.PositiveIntegerField()),
                ('procesado_en', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recompensas_diarias', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Registro de recompensa diaria',
                'verbose_name_plural': 'Registros de recompensa diaria',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='registrorecompensadiaria',
            constraint=models.UniqueConstraint(fields=('paciente', 'fecha'), name='unique_recompensa_por_dia'),
        ),
    ]
