# Generated by Django 4.2.7 on 2026-06-24 18:10

import secrets

from django.db import migrations, models


def poblar_tokens_acceso(apps, schema_editor):
    Paciente = apps.get_model('core', 'Paciente')
    for paciente in Paciente.objects.all():
        if not paciente.token_acceso:
            paciente.token_acceso = secrets.token_urlsafe(32)
            paciente.save(update_fields=['token_acceso'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_push_alarma_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='token_acceso',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='Token de acceso QR'),
        ),
        migrations.RunPython(poblar_tokens_acceso, migrations.RunPython.noop),
    ]
