# Generated by Django 4.2.7 on 2026-06-24 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paciente_token_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='citamedica',
            name='recordatorio_cuidador_enviado_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se envió el recordatorio push a los cuidadores.', null=True),
        ),
        migrations.AddField(
            model_name='tomamedicamento',
            name='alerta_cuidador_enviada_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se avisó a los cuidadores que no se registró la toma.', null=True),
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Familiar', max_length=100)),
                ('token_acceso', models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='Token de acceso QR')),
                ('activo', models.BooleanField(default=True)),
                ('vinculado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuidadores', to='core.paciente')),
            ],
            options={
                'verbose_name': 'Cuidador',
                'verbose_name_plural': 'Cuidadores',
                'ordering': ['-vinculado_en'],
            },
        ),
        migrations.AddField(
            model_name='suscripcionpush',
            name='cuidador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='core.cuidador'),
        ),
    ]
