# Generated by Django 4.2.7 on 2026-09-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_paciente_primer_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento de identidad.', max_length=20, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Si hay fecha de nacimiento, se calcula sola. Si no, puede cargarla aquí.', null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedad_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Enfermedad 2'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedad_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Enfermedad 3'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico_principal',
            field=models.TextField(blank=True, verbose_name='Enfermedad 1'),
        ),
    ]
