# Generated by Django 4.2.7 on 2026-09-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_paciente_grupo_no_definido'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='consentimiento_aceptado_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consentimiento informado aceptado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='consentimiento_firma',
            field=models.ImageField(blank=True, null=True, upload_to='consentimientos/%Y/%m/', verbose_name='Firma del consentimiento'),
        ),
    ]
